### ISSUE TITLE
copyright is not correct

### ISSUE THREAD

**Issue by morga4** [amikulich/PoltorachkaBoard#1]
expected: © 2017-2018 - Poltorachka
actual: © 2017 - Poltorachka

**Comment by amikulich** [comment]
@Sever02 
It will be fixed in the next release

**Comment by morga4** [comment]
@amikulich thank you!
I'm hoping the next release will include dev club part also
Btw, the next release are scheduled on tomorrow?

**Comment by amikulich** [comment]
@Sever02 Dev club will be released later this week

**Comment by morga4** [comment]
@amikulich thank you!
